### ISSUE TITLE
Breaking changes in pjproject

### ISSUE THREAD

**Issue by serbanman** [mgwilliams/python3-pjsip#16]
This commit in pjsip project main:
https://github.com/pjsip/pjproject/commit/22b78f901a42fc5ac4120de764a17e8a832e220e

results in this repo failing at import time:
pjsua  | Traceback (most recent call last):
...
pjsua  |   File "/app/sip/lib_manager.py", line 8, in <module>
pjsua  |     import pjsua as pj
pjsua  |   File "/usr/local/lib/python3.11/site-packages/pjsua-2.14.dev0-py3.11-linux-x86_64.egg/pjsua.py", line 60, in <module>
pjsua  |     import _pjsua
pjsua  | ImportError: /usr/local/lib/python3.11/site-packages/pjsua-2.14.dev0-py3.11-linux-x86_64.egg/_pjsua.cpython-311-x86_64-linux-gnu.so: undefined symbol: pjsua_transport_set_enable

I've also created an issue in the pjproject describing the steps:
https://github.com/pjsip/pjproject/issues/4063

**Comment by serbanman** [comment]
created a pull request:
https://github.com/mgwilliams/python3-pjsip/pull/17
