### ISSUE TITLE
Basic build instructions on Windows

### ISSUE THREAD

**Issue by IishaWu** [mgwilliams/python3-pjsip#3]
Follow https://trac.pjsip.org/repos/wiki/Getting-Started/Autoconf and build pjsip with the shared library option enabled:
Hello, I try to compile pjsip on windows10 by visual studio 2017.
 I add C:/Python24/include and C:/Python24/libs in python_pjsua property vcc++ dictionary. Then, I need to build the python_pjsua.
However, it will show an error.
LNK1104: cannot open file 'python24_d.lib'

**Comment by bltzmnn** [comment]
I got the same problem by windows 7 ,python 3.6 and vs 2015.Maybe you need to add link directory or edit additional dependencies in your python_pjsua property. And it's python 3, not python 2.4 . But I got new problems , and I give up.

**Comment by mgwilliams** [comment]
@IishaWu Like @bltzmnn said, you need to link to Python3 to use this project. Unfortunately, I cannot provide any support as to how to do that on Windows...

**Comment by addyuchiha** [comment]
hello i am addy can you help me with this error

Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/usr/local/lib/python3.10/dist-packages/pjsua.py", line 60, in <module> import _pjsua ImportError: libpjsua.so.2: cannot open shared object file: No such file or directory
